---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: npm-install
  image: node:8-alpine
  commands: ["npm install"]

- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: test-node-8
  image: node:8-alpine
  commands: ["npm run test -s"]

- name: test-node-10
  image: node:10-alpine
  commands: ["npm run test -s"]

- name: set-ci-info
  image: node:10
  commands: ["npx set-ci"]

- name: pre-release
  image: livingdocs/server-base:8.2
  commands: ["git fetch --tags"]

- name: release
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 074ac25eb410253b26b37fb3f167aadf26f632e42fa105ac1a38ce06aa08a86a

...
